### PR TITLE
Keymap update replacing custom actions

### PR DESCRIPTION
**Pull request by ScottChesworth**

### CODE REVIEW

**Comment by jcsteh** [comment]
I need to fix sortKeymap to get this merged. I think i see the problem, so I'll hopefully be able to do this soon... but not right now.

**Comment by ScottChesworth** [comment]
Do you want the Mac updates submitted before or after fixing sortKeymap?

**Comment by jcsteh** [comment]
I don't think it matters. If it's before, I can just run sortKeymap myself and push any changes to fix things.

**Comment by ScottChesworth** [comment]
Paging @jennykbrennan for some Mac action. Checkout this branch to get sortKeymap with Jamie's fixes, then do the key map changes, pop the reaper-kb.ini file in config/mac, run sort tool and push here. Cheers!

**Pull request merged**
