### PR TITLE
Key map corrections as requested in #476

### PR DESCRIPTION
**Pull request by ScottChesworth**
Mac tweaks made by @@KeithRempel

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Ugh. What did I do wrong this time?

**Comment by jcsteh** [comment]
Oops. That wasn't you. Looks like I broke Mac builds.

**Comment by ScottChesworth** [comment]
I saw it was something to do with the params dialog after commenting, just didn't wanna rub it in.

**Comment by jcsteh** [comment]
I see this also includes Windows key map changes. Could you please provide a summary of what has changed here across both key maps so I can put that in the commit message? I realies some of this will be copy/pasting from the other issue, but I'm kinda unclear on what has changed here especially given this also touches Windows. Thanks.

**Comment by ScottChesworth** [comment]
- Mac:
- Slash key mapped to "View: Move edit cursor to play cursor" in Main category to improve parity with Windows map.
- Moved "Quantize note's position to grid" in MIDI Editor category to Control+Shift+Q. Removed previous assignment because it clashed with a default OS shortcut to log out of current user account.
Both platforms:
- Assigned Shift+Dash to "View: Zoom out horizontally" in MIDI Editor category.
- Assigned Space to "Transport: play/stop" and R to "Transport: record" in Main (alt recording) category. This resolves an edge case where if users enabled the "Use alternate key map when recording" preference then started recording, there would've been no way to stop because nothing was mapped in that category.

**Pull request merged**
