### PR TITLE
Commented out call to translateDialog in peakWatcher.cpp 

### PR DESCRIPTION
**Pull request by ScottChesworth**
for GUI comparison, as per Jamie's suggestion in #861

### CODE REVIEW

**Comment by ScottChesworth** [comment]
@jennykbrennan, when you surface from your pit and have been adequately doused in coffee, can you compare Peak Watcher using this AppVeyor build? Try VO navigation and the tab order, let us know whether there are any differences. The reports from both navigation approaches with an unmodified snapshot are here for comparison: https://github.com/jcsteh/osara/issues/861#issuecomment-1421303467_

**Comment by jennykbrennan** [comment]
Will do.

**Comment by jennykbrennan** [comment]
Did do. No changes so far as I can tell.

**Comment by ScottChesworth** [comment]
Thanks for checking. Commencing Justin brain probe...

**Pull request closed without merging**
