### PR TITLE
Added missing report - Copy track with routing.

### PR DESCRIPTION
**Pull request by jennykbrennan**

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks. Two things:

1. This PR mentions "copy track with routing", but the action it adds support for is "Track: Copy tracks". Is this correct - i.e. does "Track: Copy tracks" copy routing - and the action is just not particularly descriptive?
2. This action needs to be added to the readme.

**Comment by ScottChesworth** [comment]
Adding this shores up an interaction with SWS. Users already receive feedback for SWS/S&M: Cut selected tracks (with routing) and SWS/S&M: Paste tracks (with routing) or items despite OSARA not being aware of those, turns out SWS are calling stock REAPER actions that OSARA does provide feedback for.
However, SWS/S&M: Copy selected tracks (with routing) wasn't talking yet, because it calls this variant of copy that OSARA didn't provide any feedback for, so Jen added it.

**Comment by jcsteh** [comment]
Got it. For future reference, having this sort of information in the PR comment or commit message would be super helpful. Thanks. :)

**Comment by jcsteh** [comment]
I think this still ideally needs a readme update though.

**Comment by ScottChesworth** [comment]
Yeah Jen, do it properly. :)

**Comment by jennykbrennan** [comment]
ugh. I never did get around to it, as you well know, Captain. :P 
and yes, sorry Jamie, my bad. 
I'll get the ReadMe updated tomorrow.

**Comment by ScottChesworth** [comment]
Is it done yet? Is OSARA still even being developed?

**Comment by jcsteh** [comment]
Given the amount of time it's taking me to review some pull requests lately, that's possibly an entirely valid question. :)

**Pull request merged**
