### PR TITLE
Report Transport: Play/stop (move edit cursor on stop) action added i…

### PR DESCRIPTION
**Pull request by ScottChesworth**
…n REAPER 6.74

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Anyone know why that didn't build on Mac? All I could find in the AppVeyor details was that it tried for 11 seconds then exited with code -1.

**Comment by jcsteh** [comment]
I don't think you did anything wrong. I think AppVeyor barfed. I've triggered a re-build, so let's see what happens.

**Comment by ScottChesworth** [comment]
Oh dear, *holds AppVeyor's hair back*

How do I trigger a rebuild from here if that happens in future?

**Comment by jcsteh** [comment]
You'll need to create an AppVeyor account. You can log in with GitHub if you like; that's how I do it. Once that's done, I should (hopefully?) be able to add you as a collaborator on AppVeyor.

**Pull request merged**
