### PR TITLE
Context sensitive envelope actions

### LINKED ISSUE #850: Can working with envelopes become more context sensitive?
During my (so far) flawed attempt to implement the reporting requested in #849, an idea occurred. As things stand, we have functions to report working with track envelopes, and best I can tell, to complete the request we'd need a bunch of new code to start reporting working with take envelopes. Instead, I'm wondering whether working with envelopes could be made more context sensitive? Here's how the UX would look from user perspective, taking our current key mappings as examples.
1. As things stand, the user selects a track, then hits Control+Alt+V to toggle track volume envelope visibility, Control+Alt+P to toggle track pan envelope, they can add Shift to those commands for pre-FX envelopes, or hit Control+Alt+F5 to toggle track mute envelope.
2. My request is that if a take is selected instead, those same keystrokes would call and report take-based equivalents of those actions where available. We have:
- Take: Toggle take volume envelope (ID 40693)
- Take: Toggle take pan envelope (ID 40694)
- Take: Toggle take mute envelope (ID 40695)
- Note that pre-FX equivalents don't exist, but perhaps if a take is selected, Control+Alt+Shift+P could do Take: Toggle take pitch envelope (ID 41612) instead.
3. Ideally our reporting would be adjusted to include the word track or take for clarity, "showed track volume envelope", "hid take pan envelope" etc.
4. If implemented, this context sensitivity would already play nice with our key map concept of track-based actions mainly involving Alt, item/take-based actions mainly involving Control. There are only a handful of free training resources that would need to be updated to reflect the change, I have access to the majority of those and know how to reach the handful of other people that would need to update theirs.
5. A while back I got a new context sensitive action from Cockos: "Envelopes: View envelopes for last touched track/item (ID 40019)". This could replace the track specific variant that's currently on Shift+L whenever we're ready to change the minimum REAPER requirement to 6.72 or newer. I'm hoping they can also provide us with a context sensitive variant of "FX: Show/hide track envelope for last touched FX parameter" if this is implemented, that would go on Control+Alt+L, so basically all of the widely used envelope stuff would be context sensitive.

I'm definitely not far enough along to write this, but I'd love it to happen, it would make working with envelopes more intuitive and squeeze more functionality onto the key map without requiring users to remember additional keystrokes. Penny for your thoughts?

### PR DESCRIPTION
**Pull request by jcsteh**
This branch does most of the work. There are a few things left to do:

1. Teach OSARA about the remaining take envelope actions. I've already added Take: Toggle take volume envelope, so you just need to add mappings for the other three.
2. Add code for the remaining context sensitive envelope actions. Again, I've implemented cmdToggleVolumeEnvelope. Just follow that pattern for the other three.
3. Update the readme, which I haven't touched here.
4. Update the key map, either in this PR or another one.

@ScottChesworth , want to take a stab at the remaining work here? You can just check out this "takeEnv" branch and add commits to it.

Fixes #850. Partially addresses #849.

### CODE REVIEW

**Comment by Lo-lo78** [comment]
@jcsteh 
This build works perfectly.
The action of OSARA works well:
"OSARA: Toggle track/take volume envelope (depending on focus)"
It would be very useful if the actions for the track and take envelopes were linked with focus:
"Track: View envelopes for current/last touched track id 40292"
"Take: View take envelopes for last touched/first selected item 41974"
This way with the first action selecting the track opens the envelopes window for the track with the first action. If we select an item with the second action, the take envelope window opens.
Greetings!

**Comment by ScottChesworth** [comment]
> This branch does most of the work. There are a few things left to do:
> 
Thanks! I think I get how to do the rest of it. Let's see what can possibly go Wrong :)

**Comment by ScottChesworth** [comment]
> It would be very useful if the actions for the track and take envelopes were linked with focus:
> 
I've already had Cockos make a native REAPER action that does this:
Envelopes: View envelopes for last touched track/item
I'll be binding that action to Shift+L on the key map as part of this context sensitive approach.

**Comment by jcsteh** [comment]
@ScottChesworth , are you actively working on this? Otherwise, I'll try to get it nailed when I get a sec. I'm going to have to resolve merge conflicts anyway.

**Comment by ScottChesworth** [comment]
Haven't been working on it yet no, busier week than expected. I'd still like to do it though for the learning, have got some time tonight.

**Comment by ScottChesworth** [comment]
I'll give it a shot but yeah, might need you to clean up, not very familiar with those header files yet.

**Comment by ScottChesworth** [comment]
I've had a shot at this and am stuck. This is me calling for a code paramedic (but please only look in to laugh at my weak vital signs when you're off duty). :)

Following patterns with vague comprehension dawning along the way, here's what I've added so far (which builds, but doesn't work in practice).

In reaper_osara.cpp, you did:
{ MAIN_SECTION, {DEFACCEL, "OSARA: Toggle track/take volume envelope (depending on focus)"}, "OSARA_TOGGLEVOLUMEENVELOPE", cmdToggleVolumeEnvelope},

So I added:
{ MAIN_SECTION, {DEFACCEL, "OSARA: Toggle track/take pan envelope (depending on focus)"}, "OSARA_TOGGLEPANENVELOPE", cmdTogglePanEnvelope},

As I understand it, that creates the equivalent OSARA action for pan. Its name and ID do appear in the action list.
You've mapped to cmdToggleVolumeEnvelope, so then I hopped over to envelopeCommands.cpp.

In envelopeCommands.cpp, you did:
void cmdToggleVolumeEnvelope(Command* command) {
	if (fakeFocus == FOCUS_ITEM) {
		cmdhToggleTakeEnvelope(40693); // Take: Toggle take volume envelope
	} else {
		cmdhToggleTrackEnvelope(40406); // Track: Toggle track volume envelope visible
	}
}

So I added:
void cmdTogglePanEnvelope(Command* command) {
	if (fakeFocus == FOCUS_ITEM) {
		cmdhToggleTakeEnvelope(40694); // Take: Toggle take pan envelope
	} else {
		cmdhToggleTrackEnvelope(40407); // Track: Toggle track pan envelope visible
	}
}

I think these functions are saying if fake focus is equal to a selected item, use this take-based action, else we assume it's a track selection, so use this track-based one instead.

I noticed cmdh in your function, so I opened envelopeCommands.h.

In there, you've done:
void cmdToggleVolumeEnvelope(Command* command);

So I did:
void cmdTogglePanEnvelope(Command* command);

Scons builds successfully, but when I bind Control+Alt+P to the new OSARA Toggle track/take pan envelope action, I get no report if a track is selected, and a report of "no envelopes toggled" if a take is selected. Interestingly, once a take has been selected, the report stays the same even if I reselect the track. I feel like that's probably a clue, but can't quite put my finger on what I've missed.

Any pointers appreciated (but preferably not pointers in the C++ sense of the word because I still don't really know what those are...)

Newbie is lolloping off for some dinner now. Maybe chewing will help. #IHateComputers

**Comment by jcsteh** [comment]
Honestly, I don't know why that isn't working. It all looks correct. Are you able to commit and push what you've got to this takeEnv branch and I'll try to debug it? Don't worry about breaking anything; I can always undo it if I need to.

**Comment by ScottChesworth** [comment]
Paging @JennyKBrennan, we has a Mac build available. Can you do mapping?

**Comment by jennykbrennan** [comment]
Can do.

**Pull request merged**
