### PR TITLE
Add a "Report full time for time movement commands" configuration option.

### LINKED ISSUE #613: Ability to toggle complete speaking of position on/of
Thanks Jamie for reminding me to post this as a new issue.  I thought I already had but was apparently wrong!

Currently Osara speaks only the part of the position / time info that is unchanged.  I sometimes find that this incomplete feedback is misleading when moving to a new position and can lead to confusion.  I understand this saves speech feedback for some but would like the ability to have the entire time spoken after using such navigation commands.  Perhaps a toggle for this could be added to the Osara configuration settings.

--Pete

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #613.

@ptorpey, @Ambro86, could you test a build from here and let me know if this works for you?

### CODE REVIEW

**Comment by Ambro86** [comment]
Thanks a lot! I've tried it on Windows and all works perfectly!

**Comment by jcsteh** [comment]
This is going to need a complete refactor to handle item/envelope point navigation.

**Comment by jcsteh** [comment]
Assuming this builds successfully, this is ready for another round of testing. This now reports full times for item navigation, envelope point movement, etc. if appropriate. I've also refactored the time formatting code so future code can easily benefit from this setting. There are still cases where we force caching or force no caching; e.g. reporting selection always forces caching, while second and subsequent presses of item edge movement commands always cache (since you're presumably pressing them rapidly at that point and have sufficient context from the previous press).

**Comment by Ambro86** [comment]
Hi, thanks, but this exe file is seen as a virus by windows defender.
Why didn't this happen in previous builds?

2022-08-24 13:51 GMT+02:00, AppVeyorBot ***@***.***>:

**Comment by jcsteh** [comment]
Unfortunately, that happens semi-regularly. OSARA installers aren't
Authenticode signed, so it's hit and miss as to whether Defender likes them
or not. I can tell you that these are built on a service which uses clean
virtual machines for each build, so there's pretty much 0 chance there is a
virus.

**Comment by ptorpey** [comment]
Looks good on Windows.  Thanks for addressing this.  Very nice.

 

--Pete

**Comment by Ambro86** [comment]
I've tried it on Windows and is all ok! Thanks!

2022-08-24 19:34 GMT+02:00, ptorpey ***@***.***>:

**Comment by TimNoonanVoice** [comment]
The new time setting Seems to work correctly on Mac as well.

thanks



On 24 Aug 2022, at 9:49 pm, James Teh ***@***.***> wrote:


Assuming this builds successfully, this is ready for another round of testing. This now reports full times for item navigation, envelope point movement, etc. if appropriate. I've also refactored the time formatting code so future code can easily benefit from this setting. There are still cases where we force caching or force no caching; e.g. reporting selection always forces caching, while second and subsequent presses of item edge movement commands always cache (since you're presumably pressing them rapidly at that point and have sufficient context from the previous press).

**Comment by ptorpey** [comment]
Very nice.  Working very well here in Windows also.  Implementing this in Osara itself is a much cleaner solution than having to import the keymap and LUA script.

 

Thanks.

 

--Pete

**Comment by Ambro86** [comment]
Thanks a lot! I will try this last version. How to activate the full
report of time? Or is actived by default?
Thanks.

2022-05-01 12:39 GMT+02:00, AppVeyorBot ***@***.***>:

**Pull request merged**
