### PR TITLE
Major keymap update

### PR DESCRIPTION
**Pull request by RDMurray**
Keymap update with the following changes:

## Current Issues:
1. Robbie: these actions need to have feedback implemented:
- Track: Toggle track solo defeat	<41199>
- Control+Shift+A:	Edit: Select all notes starting in time selection	<40877>
2. Scott: These OSARA actions aren't available in the MIDI Event List Editor category yet. Could they be? Listed in order of suspected usefulness.
Robbie:  We could only add the OSARA actions, the cc actions are built in to reaper.  I suspect the previous and next item commands would work, but there would be no feedback if focus was on the listview.  Since there is no feedback anyway, these could use the built-in actions "Activate next MIDI item" and "Activate previous MIDI item"
Scott: gotcha. I wonder whether it'd work to make two custom actions, move to previous/next items, then run OSARA: Focus event nearest edit cursor? I'll experiment.
Control+LeftArrow:	OSARA: Move to previous midi item on track	<_OSARA_MIDIPREVITEM>	r
Control+RightArrow:	OSARA: Move to next midi item on track	<_OSARA_MIDINEXTITEM>	r
Alt+Shift+a:	OSARA: Select all notes with the same pitch within time selection	<_OSARA_SELSAMEPITCHTIMESEL>

## Up for consideration: (all mapped on Windows for testing on Sep 22nd by Scott, and duplicated on Mac by Garth )
Control+F5:	Item properties: Toggle mute	<40175>
Control+F6:	Item properties: Toggle solo exclusive	<41561>
Alt+F5:	Track: Unmute all tracks	<40339>
Alt+f6:	Track: Unsolo all tracks	<40340>
Alt+f7:	Track: Unarm all tracks for recording	<40491>
Alt+PageUp:	SWS: Select nearest previous folder	<_SWS_SELNEARESTPREVFOLDER>
Alt+PageDown:	SWS: Select nearest next folder	<_SWS_SELNEARESTNEXTFOLDER>
Control+UpArrow:	Xenakios/SWS: Nudge active take volume up	<_XENAKIOS_NUDGETAKEVOLUP>
Control+DownArrow:	Xenakios/SWS: Nudge active take volume down	<_XENAKIOS_NUDGETAKEVOLDOWN>
Control+Shift+UpArrow:	Xenakios/SWS: Nudge item volume up	<_XENAKIOS_NUDGEITEMVOLUP>
Control+Shift+DownArrow:	Xenakios/SWS: Nudge item volume down	<_XENAKIOS_NUDGEITEMVOLDOWN>
Alt+Shift+UpArrow:	Xenakios/SWS: Nudge volume of selected tracks up	<_XENAKIOS_NUDGSELTKVOLUP>
Alt+Shift+DownArrow:	Xenakios/SWS: Nudge volume of selected tracks down	<_NUDGSELTKVOLDOWN>
Control+Win+F6:	Track: Toggle track solo defeat	<41199>
Control+Win+Shift+F6:	Track: Unset track solo defeat (all tracks)	<40770>

## Adjustments made by Scott on Sep 24th, and mirrored on Mac:
Actions to report track muting, soloing, arming, monitoring and polarity reverted to Control+Shift modifiers.
Control+Alt+Shift+M:	View: Toggle master track visible	<40075>
Control+Alt+M:	OSARA: Move last focused stretch marker to current edit cursor position	<_OSARA_MOVESTRETCH>
Alt+F11:	OSARA: Report Peak Watcher value for channel 1 of first track	<_OSARA_REPORTPEAKWATCHERT1C1>
Alt+F12:	OSARA: Report Peak Watcher value for channel 2 of first track	<_OSARA_REPORTPEAKWATCHERT1C2>
Alt+Shift+F11:	OSARA: Report Peak Watcher value for channel 1 of second track	<_OSARA_REPORTPEAKWATCHERT2C1>
Alt+Shift+F12:	OSARA: Report Peak Watcher value for channel 2 of second track	<_OSARA_REPORTPEAKWATCHERT2C2>
Alt+F10:	OSARA: Reset Peak Watcher for first track	<_OSARA_RESETPEAKWATCHERT1>
Alt+Shift+F10:	OSARA: Reset Peak Watcher for second track	<_OSARA_RESETPEAKWATCHERT2>
Logic for reworking Peak Watcher: reporting is handled with F11 and F12 keys which are easier to locate tactilely.
Added a few custom actions:
Alt+F8:	Custom: Turn record monitor off for all tracks	<_2ac072947cfcea468ba95c849876a5d5>
Alt+F9:	Custom: Reset phase for all tracks	<_56eb214e1588154aa780c625cf2b8f6f>
Note: Cockos are slower than usual at the moment, so I made custom actions to handle resetting monitoring and phase. If Cockos provide, we can reassign to native actions in due course.
Control+Alt+Home:	Custom: Select and move to first track	<_55b51a6cfddceb4b8e7871cf57daa3c9>
Control+Alt+End:	Custom: Select and move to last track	<_a3f649e75e94d643b8bd15214602a895>
Control+Alt+Shift+Home:	Custom: Select and move to master track	<_fed11423fb7353439398b16304f5e79f>

## Adjustments made by Scott on Sep 26th:
Reverted all previously proposed Control+Alt+Shift modifiers for working with the master.   - track apart from Control+Alt+Shift+M to toggle its visibility, the logic for that one being Control+Alt actions tend to be toggles in the TCP, add Shift for master. Now all actions pertaining to master will use the Shift modifier to preserve the majority of existing assignments, with only` the following actions being moved:
Shift+F5:	Track: Toggle mute for master track	<14>
Shift+F6:	Track: Toggle solo for master track	<15>
Shift+F11:	Track: Nudge master track volume down	<40744>
Shift+F12:	Track: Nudge master track volume up	<40743>
Tweaked the custom action for moving to the master track to include handling visibility. Behaves reliably now, so far as I can tell.
Control+I:	Insert media files...	<40018>

## Adjustments made by Scott on Sep 27th (Mac should already be in line with these, as they were proposed by Garth):
Control+F7:	Item properties: Set take channel mode to normal	<40176>
Control+F8:	Item properties: Set take channel mode to mono (downmix)	<40178>
Control+F9:	Item properties: Set take channel mode to mono (left)	<40179>
Control+F10:	Item properties: Set take channel mode to mono (right)	<40180>
Duplicated most NumPad functionality in the piano roll over to qwerty, see MIDI Editor section below for documentation.

## Adjustments made by Scott on Sep 28th, and mirrored on Mac:
Changed P back to Normal scope because Global was overriding first letter navigation. Have reported this to Cockos.

## Adjustments made by Scott on Sep 29th, and mirrored on Mac: 
Shift+;:	<Move edit cursor to previous tempo or time signature change	<41820>
Shift+':	Move edit cursor to next tempo or time signature change	<41821>
Control+;:	Item: Go to previous stretch marker	<41861>
Control+':	<Item: Go to next stretch marker	<41860>

##Adjustments made by Scott on Oct 7th, and mirrored on Mac:
Control+Alt+F2:	SWS: Set track name from first selected item on track	<_SWS_NAMETKLIKEITEM>

## Additional custom actions added to Mac by Garth on Oct 9th (now mirrored on Windows)
Alt+Win+Up (Mac Control+Up):	Custom: Solo exclusive previous track	<_ce078dd0845b44aebcc49334dfa669c6>
Alt+Win+Down (Mac Control+Down):	Custom: Solo exclusive next track	<_0560a0aa82a4473b9a964e7de01e588f>

##Adjustments made by Scott on Oct 19th (and done on Mac):
Alt+W:	OSARA: View Peak Watcher	<OSARA: View Peak Watcher>

##Adjustments made by Scott on Oct 20th (and  done on Mac):
Control+Windows+,:	Custom: trim left edge of items respecting ripple	<_e85f8b38153399499e2e176a8bcec06c>
Control+Windows+.:	Custom: trim right edge of items respecting ripple	<_0e77201d60c10d4d844fe05ac22623e1>

##Added to Mac on Oct 20th (mirrored on Windows)
Control+Alt+0:	Item properties: Reset item take gain to +0dB (un-normalize)	<40938>
Windows+Shift+,:	Item edit: Trim left edge of item to edit cursor	<41305>
Windows+Shift+.:	Item edit: Trim right edge of item to edit cursor	<41311>

## Proposed Media Explorer Changes (all mapped on Windows for testing on 22nd Sep by Scott. And mirrored on Mac:
Control+Space:	Preview: Play/pause	<40025>
Control+Shift+Space:	Autoplay: Toggle on/off	<1011>
LeftArrow:	Preview: Rewind a little bit	<40033>
RightArrow:	Preview: Fast forward a little bit	<40034>
Shift+LeftArrow:	Preview: Rewind to start	<40031>
Placeholder: Scott asked Piotr for the exact name of the accompanying action that jumps to the end of the file being previewed (as mentioned in his Media Explorer demo. Piotr now can't find it. Neither can I, and I've been right through the Media Explorer category. Requested from Cockos on Sep 22nd. Shift+RightArrow kept vacant, just in case.
Alt+PageUp:	Browser: Go to previous folder in history	<1450>
Alt+PageDown:	Browser: Go to next folder in history	<1451>
Control+F4:	Close Media Explorer window	<40069>
Control+W:	Close Media Explorer window	<40069>

## Removed From Media Explorer Category:
Home: because when unassigned, it moves to the top of the current folder, more convensional UX.
End: see above.
UpArrow: keyboard navigation seems more reliable unassigned.
DownArrow: see above.

## Agreed and Assigned in Main Category (Scott checked accuracy of Windows map on Sep 22nd, Mac map checked by Garth  on Sep 24th:
Alt+Shift+X:	Options: Toggle auto-crossfade on/off	<40041>
E: SWS/PADRE: Envelope processor _PADRE_ENVPROC
Shift+L:	Track: View envelopes for current/last touched track at mouse cursor	<41975>
Alt+Shift+P:	Options: Cycle ripple editing mode	<1155>	r
Control+Shift+P:	OSARA: Report ripple editing mode	<_OSARA_REPORTRIPPLE>	r
Alt+P:	OSARA: View parameters for current track/item (depending on focus)	<_OSARA_PARAMS>	r
G:	Options: Show snap/grid settings	<40071>
Alt+D:	Track: Duplicate tracks	<40062>
D:	Item: Dynamic split items...	<40760>
Control+L:	Item: Set item end to source media end	<40071>
Alt+L:	OSARA: Select next track/take envelope (depending on focus)	<_OSARA_SELECTNEXTENV>	r
Alt+Shift+L:	OSARA: Select previous track/take envelope (depending on focus)	<_OSARA_SELECTPREVENV>	r
Control+Shift+L:	OSARA: Report global / Track Automation Mode	<_OSARA_REPORTAUTOMATIONMODE>	r
Control+Shift+\:	OSARA: Cycle automation mode of selected tracks	<_OSARA_CYCLETRACKAUTOMATION>	r
Alt+Shift+\:	OSARA: Cycle through midi recording modes of selected tracks	<_OSARA_CYCLEMIDIRECORDINGMODE>	r
Control+Alt+Shift+L:	OSARA: Toggle global automation override between latch preview and off	<_OSARA_TOGGLEGLOBALAUTOMATIONLATCHPREVIEW>	r
Control+B:	SWS/S&M: Toggle all take FX bypass for selected items	<_S&M_TGL_TAKEFX_BYP>
Alt+Shift+B:	Track: Toggle FX bypass on all tracks	<40344>	r
Alt+-	Tempo: Decrease current project tempo 01 BPM	<41130>	r
Alt+=	Tempo: Increase current project tempo 01 BPM	<41129>	r
Alt+Backspace	SWS/BR: Options - Toggle "Playback position follows project timebase when changing tempo"	<_BR_OPTIONS_PLAYBACK_TEMPO_CHANGE>	r
Control+Alt+Backspace:	Item properties: Set item rate to 1.0	<40652>
Control+Shift+F2:	Xenakios/SWS: Auto-rename selected takes...	<_XENAKIOS_AUTORENAMETAKES>

## Mac Exceptions:
Control+W:	Automation: Write current values for all writing envelopes from cursor to end of project
Command+W:	Close current project tab
Duplicated all Windows assignments to set grid size in both Main section and MIDI editor on Control+Shift+1-0. This is a workaround to avoid conflicts with a number of Mac OS default keystrokes on the Command+Shift+number row.
Item properties: Toggle mute, Item properties: Toggle solo exclusive on Mac Control F5 and F6 to avoid Command+F5 which toggles Voice Over 
 

## Removed From Main Category (will likely need re-checking on Mac, sorry Garth. Na, all good on Mac Sir Scottius ):
Removed Control+Alt+N, which was a duplicate assignment to open a new project tab for some insane reason.
Removed \ Track: Set track record mode to MIDI overdub and Shift+\ Track: Set track record mode to MIDI replace, as this functionality is now provided by Alt+Shift+\ OSARA: Cycle through midi recording modes of selected tracks
Removed "Media Key Mail" which was inexplicably assigned to Track: View envelopes for current/last touched track
Removed Y, which was assigned to Take: Activate take under mouse. That frees up the Y key and all its modifiers to be "Your Key" (a key that users can assign however they so wish).
Removed Control+Shift+PageUp and Control+Shift+PageDown, which were duplicated for moving to next beat.
Removed SWS: Select master track, from Control+Alt+Shift+M because it doesn't work as the name indicates, it actually adds master track to existing selection. Now we use Control+Alt+Shift+M to toggle visibility of the master track in line with new convensions, and we've also added Control+Alt+Shift+Home to move to and select the master track. This change freed up Control+Alt+M to move stretch markers, which in turn completes shortcut access to all top menus on Windows. Hurrah!
Removed media keys Plus and Minus, which were controlling master volume.

## Changes and Additions to MIDI Editor Category (Scott checked accuracy for Windows on Sep 22nd, and Garth checked Mac on Sep 23rd):
Control+LeftArrow:	OSARA: Move to previous midi item on track	<_OSARA_MIDIPREVITEM>	r

Control+RightArrow:	OSARA: Move to next midi item on track	<_OSARA_MIDINEXTITEM>	r
Control+F4:	File: close Window	<2>
Control+w:	File: close Window	<2>
Control+Shift+A:	Edit: Select all notes starting in time selection	<40877>
Shift+A:	Select all notes with the same pitch	<40434>
Alt+Shift+a:	OSARA: Select all notes with the same pitch starting in time selection	<_OSARA_SELSAMEPITCHTIMESEL>
Control+Alt+-:	CC: Previous CC lane	<40235>
Control+Alt+=:	CC: Next CC lane	<40234>
Control+-:	OSARA: Move to previous CC	<_OSARA_PREVCC>
Control+=:	OSARA: Move to next CC	<_OSARA_NEXTCC>
Control+Shift+-:	OSARA: Move to previous CC and add to selection	<_OSARA_PREVCCKEEPSEL>
Control+Shift+=:	OSARA: Move to next CC and add to selection	<_OSARA_NEXTCCKEEPSEL>
-:	Edit: Decrease value a little bit for CC events<40677>
=:	Edit: Increase value a little bit for CC events	<40676>
Escape:	Misc: Pass through key to main window	<40401>
[:	Misc: Pass through key to main window	<40401>
]:	Misc: Pass through key to main window	<40401>
R:	Misc: Pass through key to main window	<40401>
Alt+-:	Misc: Pass through key to main window	<40401>
Alt+=:	Misc: Pass through key to main window	<40401>
Alt+Backspace:	Misc: Pass through key to main window	<40401>
Control+Shift+0:	Grid: Set to 1/48 (1/32 triplet)	<40189>
### Duplication of NumPad functionality added to Windows map by Scott on Sep 27th (Mac already sorted by His Garthness):
G:	Edit: Make notes legato, preserving note start times	<40765>
L:	Edit: Lengthen notes one grid unit	<40446>
Alt+L:	Edit: Lengthen notes one pixel	<40444>
Shift+L:	Edit: Shorten notes one grid unit	<40447>
Alt+Shift+L:	Edit: Shorten notes one pixel	<40445>
P:	Edit: Move notes right one grid unit	<40184>
Alt+P:	Edit: Move notes right one pixel	<40182>
Shift+P:	Edit: Move notes left one grid unit	<40183>
Alt+Shift+P:	Edit: Move notes left one pixel	<40181>
V:	Edit: Note velocity +01	<40462>
Alt+V:	Edit: Note velocity +10	<40463>
Shift+V:	Edit: Note velocity -01	<40464>
Alt+Shift+V:	Edit: Note velocity -10	<40465>
N:	Edit: Move notes up one semitone	<40177>
Alt+N:	Edit: Move notes up one octave	<40179>
Shift+N:	Edit: Move notes down one semitone	<40178>
Alt+Shift+N:	Edit: Move notes down one octave	<40180>
Those assignments are now also reflected in the MIDI Event List Editor category where available.

## Resolved issues:
Resolved: Scott: In the MIDI Editor category, we have Alt+Shift+A assigned to "OSARA: Select all notes with the same pitch within time selection" (_OSARA_SELSAMEPITCHTIMESEL). This doesn't work, Reaper throws up the error "Shortcut defined, but command not found". This functionality was Robbie's work, guessing it either hasn't been submitted as a pull request yet or hasn't been merged into master. Scott will chase Robbie to check. On Mac this is not assigned at all. 
Robbie: this is now in OSARA
Resolved: Robbie: should we change ctrl+shift+a in the midi editor to "Edit: Select all notes starting in time selection", as discussed a while ago on whatsapp?
Scott: assigned on Windows map and incorporated into documentation on Sep 22nd.
Resolved: Robbie: we still need keys for the following actions in the midi editor to use the new CC functionality:
CC: Next CC lane <40234>
CC: Previous CC lane <40235>
Edit: Increase value a little bit for CC events <40676>
Edit: Decrease value a little bit for CC events <40677>
Scott: assigned moving CC lanes to Control+Alt+- and Control+Alt+=, decreasing and increasing to unmodified Dash and Equals respectively on Windows. Doesn't seem like we're gonna be able to get at MIDI Editor zoom through the API any time soon, so we may as well use these keys, in alignment with other CC related assignments being all around Dash and Equals. Control of horizontal zoom ratio is still available on the NumPad innit.
Resolved: Scott: Find an alternative assignment for Alt+M, thus freeing up all shortcuts to access top menus on Windows.
Resolved: Garth to add Control+Shift+0 "Grid: Set to 1/48 (1/32 triplet)" ID 40189 in the MIDI Editor category.
resolved: Item properties: Toggle solo exclusive <41561> already has feedback.

## Test builds
If you wish to test the current version of the proposed keymap, you can download an OSARA build with the keymap included:
- [Windows Oct 23rd release candidate](https://ci.appveyor.com/api/buildjobs/e8a0gc35gowalwcx/artifacts/installer%2Fosara_pr312-242%2Cd490c970.exe)
- [Mac Oct 23rd release candidate](https://ci.appveyor.com/api/buildjobs/oefc6glbl4nm0sfn/artifacts/installer%2Fosara_pr312-242%2Cd490c970.dmg)

### CODE REVIEW

**Comment by kara-louise** [comment]
Could you have a look at my issue #132 and make that change in the key map?

**Comment by Christianlm** [comment]
Hi.
This is an important change of the keyMap, Probably for beginners it can be more intuitive, but for people that have worked with reaper and OSARA for years it is not pleasant learn the keyMap over again.

Since OSARA has been an important accessibility-tool for years, I believe that each change in keystrokes must be justified. Radical changes such those at this time  is a bit dangerous!

This is not just my opinion, these are considerations reported  in the Italian community by people who have been working on audio for years and 
I thought it was fair and useful to report here their opinions about the keyMap as well. 
https://groups.io/g/audioreaper/topic/77038663#3122
Thanks.

**Comment by RDMurray** [comment]
@Christianlm  The justification is to make it easier to teach to new users.  There is nothing to stop anyone from continuing to use the old keymap if they want to.  This is marked as a draft because it is not yet final.  Discussions are continuing on the keymap group.

@kara-louise  I have mentioned this on the keymap group.

**Comment by ScottChesworth** [comment]
@kara-louise: E has been assigned to the Envelope Processor dialog, in line with other new assignments like D for the Dynamic Split dialog, G for Grid Settings etc. I didn't see the point in breaking everyone's muscle memory by moving Control+Alt+E, because it is a logically sound assignment when you consider that the MIDI editor can be either track or item based in Reaper Prefs, hence the Control (primarily items) and Alt (primarily tracks) modifiers hold up. OSARA doesn't support that Preference just yet, but I'm hoping that in time we'll have the resources to implement support for it.

@Christianlm: you (and indeed anyone else who wants to) are more than welcome to come and get involved in discussion of moving the key map forward. Here's the join link for the WhatsApp group where discussions take place: https://chat.whatsapp.com/BiegNDJYu160CPRLpeHWQd
As Robbie said above, our current focus is on shoring up the rationale of as many existing and new assignments as we can, in order to make such a huge key map easier to learn and retain going forward. Sometimes, such change will unavoidably require an adjustment period for existing users. I appreciate that will be frustrating for some, but given that OSARA hasn't had a 1.0 release yet, and given that we mention the extension being under constant development on the page that serves snapshots, I won't personally be factoring in opposition to change/improvement unless it's backed up by a more substantial line of thinking than "just keep it like this because it's always been like this". If we accepted that school of thought, there would be no room for OSARA to grow and improve.

**Comment by kara-louise** [comment]
@ScottChesworth That's fair enough. My  main concern was the inline editor being assigned to a key because of it's inaccessibility, and if that binding as been removed, that's fantastic. 
Speaking from my experience, I've called it up by accident quite a few times without realising and wondered why the arrows stopped working as they should.

**Comment by RDMurray** [comment]
I will keep the first comment updated with the latest information.

**Comment by CastleStarter** [comment]
Hi, after a few days use these are my comments.  Quite a few are requests.  In general, get along fine with the new keymap.  For example, when pressing D didn't duplicate my track I thunk a bit and pressed alt D and hey presto all was good.

Midi editor:
Want a keystroke for toggling step recording and want it echoed  In fact, when the midi editor opens could it announce if step recording is on?
want a keystroke for action move to end of selected events in active midi media item
Pasting with control shift V, to keep position in measure, seems to throw me to the end of the measure.  Not a key map issue this.
When you are on a chord the up and down arrow keys I think are the wrong way around.  Pressing up goes down in pitch where it would seem more natural to go up in pitch.  

Main view:
backslash and shift backslash used to be mapped to overdub and not overdub recording modes  Have these gone for a reason?
prev and next presets on active FX on active track  - possibly assign to backslash and shift backslash though (conflicts with other suggestion)
alt dash and equals decrease and increase project tempo by one.  Any place to put changes in steps of 10?  Perhaps alt num pad plus and minus?
To show the last touched parameter envelope ? Is still control alt L  Can we get voice feedback?

FX window:
Any chance of getting  control tab and control shift tab to move through tabs e.g. reaEQ?  This probably isn't a keymap thing.


Regards,

Chris G

**Comment by MatejGolian** [comment]
I finally took the new keymap for a spin and I like the improvements - mainly the attention to MIDI CCs. I do have a couple of ideas/requests though and so, since I don't use WhatsApp any more, @RDMurray and @ScottChesworth, I would be interested to know what you and the WhatsApp group think about them.
First off, I think having a shortcut for deleting all CCs in a given lane at once would be great.  It doesn't have to be 'all' in the strict sense of the word - maybe it could be restricted to the time selection only, but perhaps there's room for both, as we have 2 delete shortcuts when it comes to envelope points and I think that MIDI CCs are similar in a lot of ways. And this brings me to my next point.
Since CC lanes are quite similar to track envelopes, wouldn't it make sense to use the shift key as the main modifier instead of CTRL? That way we could for example use alt + shift + dell or ctrl + shift + dell to delete all CCs in lanes and it would make for a more consistent user experience. Of course, this would mean that the scope of more keyboard shortcuts would have to be redefined. True, we'd lose the ability to work with envelope points from inside of the MIDI editor, but how often does one want to modify track envelopes when editing MIDI data anyway? Another thing I'm lacking a tiny bit is the ability to insert CC events directly. I don't know how you do it, but I usually just insert a note and than edit it so it becames a CC. This hinders the workflow a little IMO and furthermore I believe that having the option to insert CCS with a press of a keystroke would make sense - especially if the ability to delete all CCs in a lane also were to be added. Following the track envelope logic, shift + e and alt + shift + e seem like viable alternatives.
So yeah, generally I propose to treat MIDI CCs and CC lanes as equivalents to track envelopes and envelope points when it comes to shortcut assignments if possible. In this vain alt + l and alt + ; seem like natural candidates for selecting the previous and next CC lanes respectively. Of course, alt + l currently lenghtens notes by one pixel in the MIDI editor, so that would have to be reassigned to something else. Connected to this, currently alt + shift + l and alt + l are used for switching between track envelopes, so it would be more logical to use the same key combinations in both cases. What do you think? Perhaps my suggestions are quite radical, but my philosophy is that consistency comes first and I think that this would make working with CC data much more intuitive.
I also have one feature request. Could the commands "Markers: Go to previous marker/project start" and "Markers: Go to next marker/project end" become global? I find myself wanting to do it often from within the MIDI editor.
Thanks for reading.

**Comment by MatejGolian** [comment]
I have tested my main suggestions and while they themselves work fine, I have realized that remapping the MIDI editor shortcuts based on the L key would cause inconsistencies with the other MIDI note actions. Doing it the other way around = unifying the track envelope commands with the current CC lane shortcuts would perhaps be simpler, but even that would necessitate remapping other stuff, so I don't know... Be as it may, I wanted to put it out there. Who knows... Perhaps it sparks more ideas.

**Comment by RDMurray** [comment]
@jcsteh  this is ready to merge if you are happy with the changes.

**Comment by jcsteh** [comment]
Thanks to all involved for the heroic effort put into this.

**Comment by tbdalgaard** [comment]
The only inconsistency I notice is that alt-b shows the virtual midikeyboard and b bypass tracks fx. If we still want to stick to the concept that the alt key deals with track actions this could maybe be changed for a future release.
I still haven't figured out why the shortcut for move to next stretch marker in an item doesn't work in my setup, but I guess this is rarely an issue for other users on either Windows or Mac. Tested on Mac OS only here.
Thank you for a fantastic update to the keymap!

**Comment by ScottChesworth** [comment]
Hi Thomas,

I floated that point on The KeyMap Consortium group. The consensus was to leave it as is for now. It's not ideal in terms of consistency that there are still some track related actions that don't involve the Alt modifier, but trouble is, changes such as Alt+F would block menu access on Windows, which is something we worked hard to unblock. It's a tricky one. If you use WhatsApp and would like to join the discussion, I can shoot you a join link for the group. Just lemme know if that's of any interest.

**Pull request merged**
