### PR TITLE
Report the cursor position after dismissing the Jump to Time dialog.

### LINKED ISSUE #1041: When REAPER's jump dialog closes, can OSARA report the new edit cursor position?
If possible, it would be excellent to hear the new edit cursor position as validation. At the moment we hear REAPER's title bar being reported, which confirms that the dialog has been closed, but doesn't confirm where the user has jumped to.

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #1041.

@ScottChesworth, is this what you're after?

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Is there a low effort way to experiment with a short delay before the report @jcsteh? Only way I know to do that is sleep for an amount of ms, I'm guessing you'll have a more elegant way?

**Comment by jcsteh** [comment]
Sleeping would block the entire UI thread, so that's not an option. We can set a timer instead. However, I think this is risky and brittle and it leads me to question whether we should drop this idea. A timer is likely to be unreliable across different systems. Also, it might interrupt legitimate speech triggered by the user; e.g. if they quickly pressed a command after dismissing the jump dialog.

**Comment by ScottChesworth** [comment]
Hmm, tricky. I can't find any obvious way to disrupt it from working on Windows and it's so nice and I really, really want to keep it lol.
Can we try a short timer, say 150ms just to see whether that shores things up for the Mac folk? FYI we've already got Piotr (who has a decently powerful modern Mac) and Jen (who has a thing that's almost steam punk) here to test the result.

**Comment by ScottChesworth** [comment]
Another thought/question, I've already had Jen verify that on the same Mac, her report when choosing to go to a track from the More context menu in Params dialog was consistent. What's the difference? Is it that the window redraws when the jump dialog closes, but it doesn't when our params dialog gets destroyed?

**Comment by jcsteh** [comment]
I honestly have no idea why it's different.

**Comment by jcsteh** [comment]
Let's start with 50 ms. Also, if we go down this path, I'll want to rewrite this code properly, but this will do for testing.

**Comment by jennykbrennan** [comment]
Right. So now it works more than it fails. And it seems like it was the 21st track that made it fail in this particular project with empty tracks. So yep, this is way better, not a hundred percent but close in this case

**Comment by jcsteh** [comment]
Thanks for testing. The fact that you can get it to fail at all in a mostly empty project does not bode well for larger projects or higher resource usage. :(

**Comment by pitermach** [comment]
Fwiw, I just got this new version and tried to stress test it by having 40 tracks of a very resource intensive plugin which on-top of things was also running under Rosetta, and while everything else started lagging, I couldn't get the time announcement to break and I tried at least 10 times. Perhaps it would be different on an older system or if this project had a lot of items on it, but either way after this update things are much more consistent on my end.

**Comment by ScottChesworth** [comment]
Solid here on Windows. Re Mac support, so long as it's working the majority of the time, and there aren't any actual regressions being caused when it fails, I reckon we could go with that. There are already weirder things about Mac out in the wild.

**Comment by jennykbrennan** [comment]
Yep, stress test here and no fails on an older iMac.
There's one note to take  here though when dealing with the mac. @ScottChesworth. We do need to recommend keeping cursor tracking off and/or make sure mouse cursor do not speak after delay. It should be a standard recommendation for Reaper IMO, but until this, it wasn't a concern for me as infrequent user it's not a problem. But it overrides this nicely I noticed. :) 
But really, that's just one of those mac quirks. Voiceover settings can break just about anything. I'll just file that under things to be aware of. (Possibly update the Voiceover tutorial coming up. Urgh.)

**Comment by jennykbrennan** [comment]
I had a sneaking suspicion that the mouse cursor speak and cursor tracking might be the only actual problem here. So I installed the first build again. And with cursor tracking off, there are no fails at all. In other words, it works perfectly.  As long as the mouse cursor hint thingy is turned off. It's strange though as now, I can't get it to work properly at all when cursor tracking is on. 
So the first test I did makes no sense as it did work partially. This time it's either working or not working depending on that setting. 
Ultimately, as far as I'm concerned this is all good to go. Delay included or no. 

It's curious though. @pitermach , have you found the same? Since our initial tests were both partial fails, I wonder how do you have your cursor tracking set and does it make the same difference as on my machine?

**Comment by jcsteh** [comment]
What are the default cursor tracking/mouse hint settings? In other words, does this work with defaults?

I'm trying to work out whether we land this with no delay or delay. I'd prefer to land it with no delay if that really does work with default settings, but if it doesn't, then we obviously need to land it with a delay.

**Comment by jennykbrennan** [comment]
So unfortunately, cursor tracking is on by default. 
As far as mouse hints go it really doesn't seem to matter. A quick test today showed that I had mine turned off, but cursor tracking still broke this.  
So I will in fairness to mouse cursors of the world have to remove mouse hints from a potential cause here.

So it did appear to me that the only problem was cursor tracking and that the delay made no difference in my case. But I'm a sample size of one and wanted confirmation from someone before saying I'm sure.

It being a default setting is irritating, but mac users are, or at least they should be, used to turning this on and off a lot. It is needed in the midi editor event list at the moment, as just one example. It's just one of those toggle things we need to remind users about over and over, like Quick nav.

**Comment by jcsteh** [comment]
Given that cursor tracking on is default, it'd be good if we could get this working with cursor tracking on as well, so I'll wait for @pitermach to comment as to experiences with that before making a decision about delay vs no delay. Aside from my previous arguments regarding delay being brittle, delay is clunkier for users on Windows - you hear a speech hiccup with delay that you don't really notice with no delay - so I'd really prefer no delay... but I'd also prefer to avoid differences across platforms, so there are a lot of trade-offs here.

**Comment by pitermach** [comment]
All my testing was done with cursor tracking turned on, and I've never seen it cause issues in Reaper.Then again, I don't really use the event list in a MIDI editor often, so I could have very well missed that part.One thing I do have turned off, and I think it is also the default setting that's mouse-related, is I don't have the mouse cursor following voiceover.I have seen that cause issues in many places, like context menus in Juke's plugins and on the web, but as I said, I don't think that option is turned on by default, and cursor tracking itself didn't seem to cause issues with these announcements on my end.Sent from my iPhoneOn 11 Apr 2024, at 04:15, James Teh ***@***.***> wrote:﻿
Given that cursor tracking on is default, it'd be good if we could get this working with cursor tracking on as well, so I'll wait for @pitermach to comment as to experiences with that before making a decision about delay vs no delay. Aside from my previous arguments regarding delay being brittle, delay is clunkier for users on Windows - you hear a speech hiccup with delay that you don't really notice with no delay - so I'd really prefer no delay... but I'd also prefer to avoid differences across platforms, so there are a lot of trade-offs here.

**Comment by jcsteh** [comment]
Okay. Given that @pitermach has always had cursor tracking on and had problems with no delay but success with delay, I guess we're landing with delay.

**Comment by jennykbrennan** [comment]
Yep, thanks for verifying what I didn't realize until this morning to my bottomless irritation. lol. how I hate VoiceOver. 
Hey Apple, there is such a thing as too much choice.
I'm glad this is in the bag now though.

**Pull request merged**
