### PR TITLE
Report pitch or name when navigating to chords that only contain one …

### PR DESCRIPTION
**Pull request by ScottChesworth**
…note, bound note reporting to the relevant check box in OSARA Config, fixed missing white space when reporting muted notes

### CODE REVIEW

**Comment by jcsteh** [comment]
Note that this isn't the full info you get when moving with up and down arrows. That also reports length and velocity. Are you happy with this discrepancy? You can still get this by just pressing up or down arrow of course, but it seems odd to make this more convenient for the user but only go half way.

**Comment by ScottChesworth** [comment]
Yep that's intentional. Before this change we'd hear "1 note" from the screen reader, but hearing the preview already tells me there was a single note, so I figured we could speak the note pitch instead without adding verbeage. It'll also be a good change for JAWS/Braille display users, Snowman's scripts already print OSARA's reporting to displays, so now people can hover their finger over where the note is shown as they navigate if needed.

**Comment by jcsteh** [comment]
Okay. Happy to take this change then, but how would you feel about me submitting a follow-up to add velocity and length? My reasoning is that in many cases, I'm working with a MIDI item that mostly has single notes. Now that I get the note name, I can avoid pressing down arrow... but I still have to press down arrow to get the other info, so the advantage of the new convenience isn't fully realised. This would add additional verbiage, which I realise you were trying to avoid, but it's verbiage at the end, not the start, which means it is easily ignored or silenced.

**Comment by ScottChesworth** [comment]
Sure, I'm fine with reporting all of it if that's useful.

**Pull request merged**
