### PR TITLE
Report crop to active take

### PR DESCRIPTION
**Pull request by jennykbrennan**

### CODE REVIEW

**Comment by jennykbrennan** [comment]
Simple reporting of cropping item to active take, i.e 2 items cropped to active take, or No takes removed if none. Reports only the number of items where takes are actually removed, not the number of items selected. There may be circumstances where this could fail, but I can't think of any. Thanks to @ScottChesworth and  Toni for breaking my brainblock on this. And i can't seem to be able to tag Toni.  Anyway, thoughts on this?

**Comment by ScottChesworth** [comment]
To tag Toni, type @timtam. Tadda!

**Comment by jennykbrennan** [comment]
Cool. But he doesn't appear in the automatic list thingy, there a reason for that?

**Comment by ScottChesworth** [comment]
Hmm, dunno

**Comment by jcsteh** [comment]
Thanks. There's some minor code cleanup I'd like here - nullptr instead of 0, indentation and bracing issues, etc. - but I'll just take care of that myself when I get a chance.

**Comment by jennykbrennan** [comment]
Thanks. :)

**Pull request merged**
