### PR TITLE
Bind OSARA's note preview to Options: Preview notes when inserting or editing

### LINKED ISSUE #440: Add an option to disable note previews in the event list
In Event List mode, is it possible to turn off note previews? If not, could Osara have an option to either toggle this, or have it set in Osara configuration?

### PR DESCRIPTION
**Pull request by leonardder**
Fixes #440

### CODE REVIEW

**Review by jcsteh — CHANGES_REQUESTED** [review]
Thanks!

1. Since most of the time we just call previewNotes, would it be cleaner to just have previewNotes return early at the top if the toggle is enabled? The one exception is the event list preview, which does a bunch of other stuff, so that function should also return early at the top. Thoughts?
2. Please add a comment to the lines where the action id is used specifying the name of the action.

**Comment by leonardder** [comment]
Done as requested.

**Comment by jcsteh** [comment]
Now that previewNotes checks the toggle, it isn't needed anywhere else except the event list preview.

**Comment by leonardder** [comment]
Ugh, I'm sorry. This was my intention, but something went wrong with git.

**Comment by jcsteh** [comment]
I figured it might've been something like that. :)

**Comment by jcsteh** [comment]
Messed up a merge and had to force push, so this is now master f4f18d52.

**Pull request merged**
