### PR TITLE
Add feedback when quantizing items in TCP

### PR DESCRIPTION
**Pull request by ScottChesworth**

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Anyone know why that check failed instantly? It was saying the branches could be merged before I opened the PR.

**Comment by jcsteh** [comment]
I have absolutely no idea. I think AppVeyor is on acid.

**Comment by ScottChesworth** [comment]
Where does it get that from? Asking for a friend...

**Comment by jcsteh** [comment]
That said, I'm surprised this built for you locally. It won't build here because of the declaration in the header file.

**Comment by ScottChesworth** [comment]
What did I do wrong in there? Weird, it builds fine here.

**Comment by jcsteh** [comment]
In header files, we don't (and can't) have "using namespace std", so you have to prefix anything in the std namespace; e.g. std::string. I really don't understand why this built for you and not me. Very odd.

**Pull request merged**
