### PR TITLE
New keymap for both windows and mac

### PR DESCRIPTION
**Pull request by GianlucaApollaro**
Windows+Control+X	Item: Cut selected area of items
Windows+Control+C	Item: Copy selected area of items

Control+Shift+B	Monitoring FX: Toggle bypass
Alt+Shift+B    SWS/S&M: Toggle all take FX bypass for selected items
Control+Alt+U	Item: Glue items
Control+Shift+G	Item grouping: Remove items from group

Alt+-	View: Zoom out horizontal
Alt+=	View: Zoom in horizontal

Home	Go to start of time selection
End	Go to end of time selection
Alt+Shift+Home	Go to start of loop
Alt+Shift+End	Go to end of loop

Control+F	Item: Show FX chain for item take
Shift+E	Envelope: Insert new point at current position

Control+Shift+I	Envelope: Insert automation item

Alt+Shift+-	SWS: Recall previous snapshot
Alt+Shift+=	SWS: Recall next snapshot
Alt+Shift+Backspace	SWS: Recall current snapshot
Alt+Shift+`	SWS: Open snapshots window

Control+Shift+0	Grid: Set to 1/48 (1/32 triplet)  In both main and Midi Editor (Not possible to bind this one on my windows machine)

Shift+U  SWS/BR: Normalize loudness of selected items/tracks...

### CODE REVIEW

**Comment by jcsteh** [comment]
Sorry it took me so long to get to this.

This only includes an updated Windows key map. Did you mean to include an updated Mac key map as well? The title suggests so...

**Comment by GianlucaApollaro** [comment]
Hi, this is actually old, we have a new one coming up, Scot said he will make a new pull request with an updated keymap for both windows and mac, collaborative effort of the whole community.

**Comment by ScottChesworth** [comment]
Jamie, there's a pull request coming soon as mentioned in our email
exchange yesterday. It'll contain Windows and Mac keymaps that have
been cleaned up and tested on both platforms. I've started reading Pro
Git as recommended, but realized that it's gonna take me a while to
get to a point with submitting in a way that causes the least amount
of grunt work to be generated. In the meantime, a thoroughly pleasant
chap called Frank who has a bit more experience with Git and a lot
more of a grounding in development is currently bashing his head
against it for us to try and make sure you get something that's easier
to approve. In light of the stuff you implemented tonight, we're gonna
make a couple of additional changes (basically re-inserting a few
actions now that they provide feedback). Thanks heaps for finding the
time to close those issues.

**Comment by jcsteh** [comment]
You know what? Don't worry about Git (for now) if it's going to take too many cycles to learn. Instead, just send me an email with the updated key maps, making sure they're based off the absolute latest stuff on GitHub. However, please also:

1. Update the readme as appropriate.
2. Include an attached text file which includes all of the information about the changes. I'll use this for the commit message. So, the first line should be something like "Updated key maps for both Windows and Mac." Subsequent lines should then provide further details. This way, I can just slam this into the commit, rather than having to faf about with copying/pasting from the email and formatting screw ups that email applications introduce.

I'd obviously prefer you use Git in future, but I can live with it not being used as long as it's super easy for me to get the changes in, as above.

Closing this PR since it's out of date.

**Comment by jcsteh** [comment]
Oh, and anyone who directly contributed to updating the key map files needs to be added to the Contributors section of the readme if they aren't already.

**Pull request closed without merging**
