### PR TITLE
Use latest Visual studio 2022 image on appveyor

### PR DESCRIPTION
**Pull request by RDMurray**
Let's see if this works.

### CODE REVIEW

**Comment by leonardder** [comment]
Ugh, I guess the crash is because of these warnings. We can probably silence them somehow, though question is whether we really want to do that.

**Comment by leonardder** [comment]
It looks like it is on the radar, see https://github.com/llvm/llvm-project/issues/54487

@RDMurray If you don't mind, marking this as a draft. We'll  probably either need to wait until this has landed in Visual Studio or find a workaround that suppresses warnings or rather, doesn't let the build fail if there's a warning during linking. Please mark this ready for review when it builds correctly.

**Comment by jcsteh** [comment]
It looks like the linker doesn't exit with a failure code, but PowerShell treats this as an exception because there was output to stderr. I vaguely recall there's some way to prevent that, but I don't recall how.

**Comment by leonardder** [comment]
@RDMurray I hope you don't mind, but I just pushed a commit to your branch that will likely fix this. Let's see how the build does.

**Comment by leonardder** [comment]
Never mind, I reverted it without luck. Tried placing 2>&1 after the scons command, but it still fails. May be something Like $ErrorActionPreference = 'SilentlyContinue' might work, but that's also a bit dubious.

**Comment by leonardder** [comment]
note that continue is the default and still raises exceptions. You probably need SilentlyContinue here.

**Comment by RDMurray** [comment]
> note that continue is the default and still raises exceptions. You probably need SilentlyContinue here.

Thanks, I'll try that.

**Comment by RDMurray** [comment]
@ScottChesworth not quite yet :)  This only builds because it clears $Error which is probably not a good idea because it might hide real errors.

**Comment by RDMurray** [comment]
thanks @jcsteh  I found the command from NVDA. it is Set-AppveyorBuildVariable

**Comment by RDMurray** [comment]
That works for Windows, but cmd is no good for mac.  maybe using bash for the build script will work?

**Comment by leonardder** [comment]
With ErrorActionPreference, we need to make absolutely sure that failed builds won't report as succeeded.

**Comment by RDMurray** [comment]
It looks like appveyor sets ErrorActionPreference to Stop for each ps: command.

**Comment by RDMurray** [comment]
Indeed. Interesting that the failed build succeeds on windows, but fails as it should on Mac. Time for me to learn about PowerShell rather than stabbing in the dark. :-)

**Comment by RDMurray** [comment]
I think this should be okay now.

**Comment by leonardder** [comment]
Ugh, such an ugly script this is, credits to PowerShell for the uglyness of course. Nice you've been able to come up with this.

**Comment by jcsteh** [comment]
Thanks for your work on this. This is horrible... but that's a reflection on PowerShell and not your work. :)

**Pull request merged**
