### PR TITLE
Feb 22 key map revisions

### LINKED ISSUE #667: Key map changes for February 2022
This is a list of issues for the February Key map update, due to be merged on 2022-02-28.

# Test Builds
Please report any inaccuracies, problems or ideas in the comments below before the end of Feb.
[Windows](https://ci.appveyor.com/api/buildjobs/n88cjcv9a91s4e3d/artifacts/installer/osara_pr685-843,1c22f409.exe)
[Mac](https://ci.appveyor.com/api/buildjobs/24g4k3cd0yaxw514/artifacts/installer/osara_pr685-843,1c22f409.dmg)

### Main section
- FX: Toggle delta solo for last focused FX: Shift+F6 (replaces Track: Toggle solo for master track)
- FX: Clear delta solo for all project FX: Alt+Shift+F6
- Scrub: Toggle looped-segment scrub at edit cursor: / (replaces View: Move edit cursor to play cursor)
- OSARA: Report regions, last project marker and items on selected tracks at current position: Control+Shift+R
- Time selection: Swap left edge of time selection to next transient in items: Control+Shift+[
- Time selection: Extend time selection to next transient in items: Control+Shift+]
- OSARA: About: Control+F1
- Help: About Reaper: F1
### Media Explorer section
- Preview: decrease volume by 1 dB: Alt+Shift+DownArrow
- Preview: increase volume by 1 dB: Alt+Shift+UpArrow
### MIDI Editor section (also mirrored in MIDI Event List Editor section where available)
- Edit: Insert note at edit cursor (no advance edit cursor): I and Numpad5
- Edit: Insert note at edit cursor: Shift+I and Shift+Numpad5
- Edit: Toggle selection of all CC events under selected notes: C
- Navigate: Move edit cursor to start of selected events: Control+Shift+Home
- Navigate: Move edit cursor to end of selected events: Control+Shift+End

## Tasks
- [x] #664
- [x] #665
- [x] #430
- [x] #638 
- [x] #574
- [x] #672 
- [x] #632 
- [x] #693

### PR DESCRIPTION
**Pull request by ScottChesworth**
Windows and Mac key maps updated based on February's meta issue, plus a heap of consistency touch-ups throughout ReadMe. Ready for testing in situ. This will close #667 when merged.

### CODE REVIEW

**Comment by RDMurray** [comment]
Thanks for doing this.  It's my fault for not letting you know, but please could you use the new Keymap sorting utility on the keymap files.  It makes the diffs much smaller.  Before committing, just do:
```
python tools\sortKeymap.py config\windows\reaper-kb.ini
python tools\sortKeymap.py config\mac\reaper-kb.ini
```
Change \ to / if using bash or on mac.

**Comment by ScottChesworth** [comment]
Gotcha, will do. Is it too late to do that now that I've committed?

**Comment by RDMurray** [comment]
Not at all.  You can just sort both the keymaps and then commit again.  It shouldn't matter which OS you use to run the sorting utility, but I have only tested it on Windows.

**Comment by ScottChesworth** [comment]
Then I'd update the links in the meta issue once checks have passed, yeah?

**Comment by RDMurray** [comment]
Yes, although the keymaps should be identical, it's just the order of lines in the files that are different.  It might be a good idea to merge master into this branch to get the recent mac fix before updating the build links.

**Comment by ScottChesworth** [comment]
Good thinking. One question, how do I do that? Rebase locally and then push to this PR?

**Comment by jcsteh** [comment]
First, switch to the master branch and pull it:
git checkout master
git pull
Now switch back to your key map branch:
git checkout yourBranchName
Now you can either rebase or you can just merge. Merge clutters the commit
history a bit, but we squash merge pull requests anyway, so it really
doesn't matter:
git merge master
git push

**Comment by jcsteh** [comment]
Also, when you merge this, can you please ensure the summary of changes from #667 is included in the commit message? Thanks.

**Comment by ScottChesworth** [comment]
Urgh, somehow I ended up with a whole new PR, #683. Gonna try to figure out how to merge that here so we don't lose the discussion. Any tips on where I went wrong welcome.

**Comment by jcsteh** [comment]
It looks like you have two different branch names, Feb22KeyMap and Feb22Keymap (note the upper case m vs lower case m). That said, how did you create the pull request? I usually just do it via the web, so they never get created automatically for me.

**Comment by jcsteh** [comment]
Markdown in the commit message is fine.

**Comment by jcsteh** [comment]
Btw, when you push to a branch, you don't need to do anything on GitHub; it will just update the PR.

**Comment by jcsteh** [comment]
I closed the other PR and deleted the other branch. You'll probably have some cleanup to do on your side now, since Windows gets very confused when branches have different capitalisation (since Windows is case insensitive). If you don't have local changes, I'd suggest just deleting the branch locally with git branch -D (note the capital D), doing a git fetch and checking out the branch again: git checkout Feb22Keymap

**Comment by ScottChesworth** [comment]
>  how did you create the pull request? I usually just do it via the web, so they never get created automatically for me.
> 
Yeah, doing it in the browser here too, just somehow didn't notice it was making a new one until after I'd hit the Create pull request button. Must remember I'm still a rookie, still need to be listening to the jibber-jabber of my robot pal. I've done the cleanup here now, thanks for the rescue! :)

**Comment by jcsteh** [comment]
Ug. Looks like Xcode got updated on AppVeyor or something. I'll look into
it.

**Comment by ScottChesworth** [comment]
Thanks for fixing so fast!

**Pull request merged**
