### PR TITLE
Build for Apple silicon as well as x64.

### LINKED ISSUE #402: Inquiring about Apple silicon support
What is the status of apple silicon support? 
As OSARA is not built for arm64/M1 has anyone tested and can confirm that OSARA still works fine under Rosetta?
I know this would require devs to buy a new machine, Is that something in the works? I would be open to making that transition and being the beta guinea pig if needed.

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #402.

### CODE REVIEW

**Comment by jcsteh** [comment]
@kyleman, @ogomez92, would you mind testing [this build](https://ci.appveyor.com/api/buildjobs/7251bkfoxbn2x4g8/artifacts/installer/osara_pr451-429,0ad8531a.dmg) of OSARA with a native M1 build of REAPER? Thanks.

**Comment by jcsteh** [comment]
It'd also be good to have testing on an Intel Mac to make sure nothing broke there.

**Comment by jcsteh** [comment]
CC also @pitermach.

**Comment by tbdalgaard** [comment]
I will test this build later today if a test on Catalina is useful?

Sendt fra min iPhone via Braille Sense U2/MBraille

**Comment by jcsteh** [comment]
Yes, a test on Catalina would be useful.

>

**Comment by ogomez92** [comment]
Hello everoyne,
I can happily report success. I tested this Osara build on both an
Intel and an M1 version of reaper and it seems to work fine, at least
when creating the project and adding a few tracks.

Thanks.

**Comment by jcsteh** [comment]
Fantastic. Thanks. I'd like to get a successful report from at least one
user on Catalina or earlier before merging this.

>

**Comment by ScottChesworth** [comment]
Paging @GarthHum, he's the sort of chap who might have a bootable backup of something pre Catalina to test with.

**Comment by ScottChesworth** [comment]
Also @dgl1984, perhaps another potential purveyor of older Mac OS. Dunno how often his Mac gets switched on.

**Comment by tbdalgaard** [comment]
Just tested with
pr451-429,0ad8531a
on Mac OS Catalina 10.15
And it looks like it works as expected! I was able to get the regular tests through, that means pressing F12 and pressing some random keys and I got spoken feedback for all of it.

Are there specific tests I can do to verify this some more before any merge?


Sendt fra min Mac Mini via Apple Mail

**Comment by pitermach** [comment]
Having finally gotten my M1 Mac I can confirm that this Osara build works both with the Arm 64 build of reaper as well as the Intel one on Rosetta on my system as well.

**Comment by jcsteh** [comment]
Thanks. I think this is sufficient testing for me to merge.

**Pull request merged**
