### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by GarthHum**
Updated actions with keyboard shortcuts 
changed existing keyboard shortcuts inline with proposed key map
Fixed typo yu > you in two locations.
Added contributor

### CODE REVIEW

**Comment by jcsteh** [comment]
Thanks Garth! For future reference:

1. I tend to camel case key names containing multiple words (UpArrow, DownArrow) so they are pronounced better by speech synths. I made this change here.
2. You probably want to create a new branch based off master, rather than submitting a pull request from master itself. The other problem you're going to hit in future is that this branch needs to be based off the latest official master from me, not the copy in your fork, which will be out of date. Unfortunately, I don't see any way to sync your fork from the web interface, which kind of sucks.

**Comment by GarthHum** [comment]
Thanks Jamie
Noted re the camel case
I will try to branch again rather than fork next time. I Forked this time as I couldn’t work out how to branch, thought it might be a permissions thing but it might be a web interface thing. 
Thanks again 
Garth 
 
 

On 5 Jun 2018, at 8:49 am, James Teh <notifications@github.com> wrote:

Thanks Garth! For future reference:

I tend to camel case key names containing multiple words (UpArrow, DownArrow) so they are pronounced better by speech synths. I made this change here.
You probably want to create a new branch based off master, rather than submitting a pull request from master itself. The other problem you're going to hit in future is that this branch needs to be based off the latest official master from me, not the copy in your fork, which will be out of date. Unfortunately, I don't see any way to sync your fork from the web interface, which kind of sucks.

**Comment by jcsteh** [comment]
You need to fork and then create a branch within your fork. So forking was
the right thing to do; you can't do anything without creating a fork.
However, you then also need to branch. Think of a fork as "Garth's work",
then think of a branch as "Garth's work on this particular thing". :)

**Comment by GarthHum** [comment]
Cheers Jamie 
Thanks for your patience 

On 7 Jun 2018, at 10:06 am, James Teh <notifications@github.com> wrote:

You need to fork and then create a branch within your fork. So forking was
the right thing to do; you can't do anything without creating a fork.
However, you then also need to branch. Think of a fork as "Garth's work",
then think of a branch as "Garth's work on this particular thing". :)

**Pull request merged**
