### PR TITLE
Correct reporting of regions.

### LINKED ISSUE #442: Incorrect announcement of Regions
The semicolon and apostrophe keys move from marker to marker and also move from region to region.  When regions overlap, these keys provide incorrect feedback of the region name as well as the start and end points of the region.  Here is an example:

1.  Set edit markers at the beginnings of measures 10 and 20 using the left and right brackets.
2.  Hit Shift+R to create a region from the selected range.
3.  Hit shift+alt+R to label this "Region #2".
4.  Set edit markers at the beginnings of measures 1 and 15 using the left and right brackets.
5. Create a region by hitting shift+R.
6. Hit shift+alt+R to label the region "Region #1
7. Hit the semicolon and apostrophe keys to navigate through the markers associated with the beginnings and ends of the regions.  Here is what you will find in order::
measure 1: "start of region #1"
measure 10: "start of region #2"
measure 15: "end of region #2"
measure 20: "end of project"
Note: measure 15 is incorrectly labeled as the end of region #2
9.  You can verify the start and end of each region by hitting control+shift+alt+R to get into the Markers and Region Manager.  The start and end of each region is properly labeled in this dialog.
10. Now use the semicolon and apostrophe keys to move to measure 15.  This is reported incorrectly as the end of region #2.
11. Hit delete.
12. Instead of deleting region #2 you will find that region #1 is deleted.
Summary: The navigation commands are providing incorrect info for the region markers which can lead to errors in deleting the desired region.
10. 9.

### PR DESCRIPTION
**Pull request by jcsteh**
1. Report "region start" and "region end" instead of just "region", since the marker navigation commands move to end positions as well.
2. Correctly detect the end position of a region, even where there are overlapping regions.

Fixes #442.

### CODE REVIEW

**Comment by jcsteh** [comment]
@ptorpey, please give the test build in this pull request a try when it completes in a few minutes. It won't fix deletion, but it should fix reporting. Deletion should be fixed separately, potentially in REAPER itself.

**Comment by ptorpey** [comment]
Microsoft Defender is complaining about downloading this because of a potential virus.  Should I just turn off MS Defender?  I assume this is safe, but just checking.

 

Thanks.

 

--pete

**Comment by ptorpey** [comment]
Just to be on the safe side, I did a full backup of my system before turning off my anti-virus to download and install this build.  Yes, probably not necessary but…

 

Anyway, start and ends of regions are now correctly identified for both adjoining regions and regions that are not adjacent.  Very nice.

 

One small issue for thought depending on how easy it is to fix:

 

When I have two regions adjacent to each other, let’s say section #1 followed by section #2, here is the feedback I get as I hit apostrophe several times to move through the regions:

 

section #1 region start bar 5 
section #2 region start section #1 region end bar 10 
section #2 region end bar 15 



Note that the beginning of section #2 is announced before the end of section #1.  Logically it might make more sense to announce the end of section #1 before the beginning of section #2 when one is moving in that direction.

 

Interestingly, when I move the other way by hitting semicolon I get:

 

section #2 region end bar 15 
section #2 region start section #1 region end bar 10 
section #1 region start bar 5 



So the beginning of section #2 is properly announcd before the end of section #1 going in the reverse direction.

 

One more note.  Using JAWS you can see that I get a spoken line like:

 

section #2 region start section #1 region end bar 10

 

I assume that this really wanted to say:

 

section #2 region start bar 10 section #1 region end bar 10

 

but that the complete message about section #2 starting at bar 10 got truncated by the speech synthesizer because the second message about coming to the end of section #1 crashed into it.  That may not be fixable since it could be a timing issue.

 

Anyway, this is much better feedback than we had before since now we can reliably tell where regions start and end.

 

Thanks a bunch.  Let me know if you want me to do any more testing.

 

--Pete

**Comment by jcsteh** [comment]
> Microsoft Defender is complaining about downloading this because of a potential virus.

Yeah, Defender seems to be overzealous concerning OSARA installers unfortunately.

> Logically it might make more sense to announce the end of section #1 before the beginning of section #2 when one is moving in that direction.

I follow your logic, but on the flip side:

1. If you have adjacent regions and you're moving between them, it's likely you care more about the start of a region than the end. If the end is reported first, you have to wait until that is read before you know what region you've moved into. That's less efficient for fast movement.
2. While possible, your suggestion is not trivial to implement.

> Using JAWS you can see that I get a spoken line like: section #2 region start section #1 region end bar 10 I assume that this really wanted to say: section #2 region start bar 10 section #1 region end bar 10 but that the complete message about section #2 starting at bar 10 got truncated by the speech synthesizer

There is no truncation; this is intentional. Those commands can only move to a single position each press, so reporting "bar 10" twice is redundant.

**Comment by ptorpey** [comment]
1.	If you have adjacent regions and you're moving between them, it's likely you care more about the start of a region than the end. If the end is reported first, you have to wait until that is read before you know what region you've moved into. That's less efficient for fast movement.

[PT] By that logic one would be more interested in hearing that one is moving into a region that is earlier in the project before moving out of a later region and hearing that you are at the beginning of that later region when moving backwards through a project.  But when moving backwards the region that is later in the project is still announced prior to the next region earlier in the project that one is moving into.  The way this works now, the latest region in the project is announced first no matter which way one is navigating with adjacent items.

2.	While possible, your suggestion is not trivial to implement.

[PT] To me this is the stronger argument for keeping things the way they are now.  At least this is giving much more useful feedback than before.  As you say, a lot comes down to user preference and  sometimes one just has to make a decision to do things one way or another.  Folks will eventually get used to the chosen solution.

Using JAWS you can see that I get a spoken line like: section #2 <https://github.com/jcsteh/osara/issues/2>  region start section #1 <https://github.com/jcsteh/osara/issues/1>  region end bar 10 I assume that this really wanted to say: section #2 <https://github.com/jcsteh/osara/issues/2>  region start bar 10 section #1 <https://github.com/jcsteh/osara/issues/1>  region end bar 10 but that the complete message about section #2 <https://github.com/jcsteh/osara/issues/2>  starting at bar 10 got truncated by the speech synthesizer

There is no truncation; this is intentional. Those commands can only move to a single position each press, so reporting "bar 10" twice is redundant.

[PT] Sounds good.  Thanks and happy holidays!

 

--pete

**Comment by jcsteh** [comment]
I don't quite follow your thoughts regarding moving backwards. When moving backwards, I'd argue you're still usually more interested in moving to the start of a previous region, rather than the end. For example, if you have a song with adjacent regions verse 1 and chorus 1 and you move back by region, I'd think you more likely care about the start of chorus 1 and the start of verse 1 when moving backwards and vice versa when moving forwards. Sure, there are occasions where knowing about the end is useful (e.g. where there is space between regions), but my thinking is adjacent is more common. Granted, I have no evidence for that assertion, so it could be entirely wrong.

As you say, a decision had to be made either way. We can always adjust this later if repeated user feedback reveals productivity problems. FWIW, I'm open to adjusting, but let's give it time some to bake.

**Comment by jcsteh** [comment]
Edited my previous comment to clarify some confusion. :)

**Comment by ptorpey** [comment]
Good point.  I was mostly thinking analytically about logically moving from start to end of one region and then start to end of the next region when moving forward in a project.

Hearing the start of the first region followed by the start of the second region followed by the end of the first region and then the end of the second region just sounded a bit off to me.

 

But, as you say, in practice the method you implemented might work better.

 

In any case, the feedback now is much better and can always be changed if folks think it should be another way based on actual experience using regions.

 

--pete

**Pull request merged**
