### PR TITLE
 Key map update: "OSARA: View properties for current media item/take/…

### PR DESCRIPTION
**Pull request by ScottChesworth**
…automation item (depending on focus)" (Shift+F2) and "Xenakios/SWS: Rename takes and source files... (no undo)" (Control+Alt+Shift+F2).

### CODE REVIEW

**Comment by ScottChesworth** [comment]
Hey @jcsteh, I considered merging this small key map update, but two questions:
1. Are you ok with me starting to merge key map stuff so long as the ReadMe has been updated and AppVeyor checks pass?
2. If so, would I choose Create a merge commit, Squash and merge, or Rebase and merge?

**Comment by jcsteh** [comment]
Yes, that's fine. Please squash and merge, editing both the commit summary and commit description appropriately.

**Comment by leonardder** [comment]
@ScottChesworth Could you consider the changes listed here as well? https://github.com/jcsteh/osara/issues?q=is%3Aissue+is%3Aopen+label%3AsentToKeymapCrew

**Comment by ScottChesworth** [comment]
Will do, not today though. I've fallen behind in the key map group, need to catch up on consensuses.

**Comment by MatejGolian** [comment]
@ScottChesworth, since we're discussing keymap stuff here, what are your thoughts on my request in #585? If the keymap crew doesn't find it useful I can close the issue to reduce the number of open issues.

**Comment by jcsteh** [comment]
Thanks for your work here, @ScottChesworth. A couple of minor things to note for future merges:

1. Please include any issues fixed by the PR in the initial comment. Note that you can edit the comment later, as you would have needed to do in this case given the master i/o change. If you write "Fixes #xxx" in the initial comment (where xxx is the issue number), GitHub will link the pull request to the issue and automagically close the issue when the PR gets merged.
2. Please also include the PR number and any relevant issue numbers in the commit message. You can see 2d53ee42 for an example of how I usually write this, but there is no specific magic that happens there, so the exact format isn't super important. It's just useful when looking at the git logs to find the issue associated with a particular change.

Thanks much.

**Comment by ScottChesworth** [comment]
Gotcha, will do.

**Pull request merged**
