### PR TITLE
Set muteNextMessage to false before returning when calling handleToggleCommand

### LINKED ISSUE #914: Bug: when used in custom actions, OSARA: Mute next message from OSARA doesn't mute reports from REAPER toggles
Encountered a weird thing on Mac, @RDMurray has confirmed it also impacts windows:
1. Create a custom action with "OSARA: Mute next message from OSARA" followed by any OSARA action that reports.
2. Bind your new custom action to a keystroke and test it, you should find all is well.
3. Now create another custom action, this time with "OSARA: Mute next message from OSARA" being followed by a REAPER toggle action.
4. Bind that to a keystroke, and if what I encountered holds up, that'll still report. It shouldn't.

### PR DESCRIPTION
**Pull request by ScottChesworth**
Might fix #914

### CODE REVIEW

**Comment by ScottChesworth** [comment]
@jennykbrennan, can you see whether this fixes mute next message action on Mac?

**Comment by jennykbrennan** [comment]
Looking good. No unnecessary feedback here. Nice. 👍

**Comment by ScottChesworth** [comment]
@RDMurray, false before returning cleans up speech on Mac, but breaks the intended behaviour on Windows. It still worked fine to mute OSARA toggles here, but when I made a custom action with our mute next message then a REAPER toggle I still got the full report. Any idea why this is behaving differently on each platform?

**Comment by TimNoonanVoice** [comment]
Both with the main OSARA and with Scott's adjusted versions I get the following behaviour:

I have a custom action mapped to ctrl-shift-m that 
calls Osara mute next
and
Toggle track FX announcement.

When I run it by the keystroke, it is silent - but then my next action (such as moving to a different track) is muted.

However, the FX announcement is not toggled.

Tim



On 9 Jul 2023, at 7:34 pm, ScottChesworth ***@***.***> wrote:


@jennykbrennan <https://github.com/jennykbrennan>, can you see whether this fixes mute next message action on Mac?

**Comment by RDMurray** [comment]
@TimNoonanVoice  I think that's another bug unrelated to muting. 
  
@ScottChesworth  I haven't worked out what's going on with mac yet, But I've installed Reaper for mac and I should get to it today.

**Comment by ScottChesworth** [comment]
@TimNoonanVoice, can you try triggering that OSARA toggle from a keystroke without the mute action involved? I'd like to get confirmation that it works reliably on its own.

**Comment by RDMurray** [comment]
I suspect it's a problem with calling osara actions from custom actions. Does the problem of the toggle not working only happen on mac?

**Comment by ScottChesworth** [comment]
You suspect correct. That's broken on Windows too.

**Comment by TimNoonanVoice** [comment]
Hi all,

Should have done that earlier.

Can confirm that after removing the mute action, the toggle fx status does not seem to work on Mac.

Tim

On 10 Jul 2023, at 8:57 pm, ScottChesworth ***@***.***> wrote:


@TimNoonanVoice <https://github.com/TimNoonanVoice>, can you try triggering that OSARA toggle from a keystroke without the mute action involved? I'd like to get confirmation that it works reliably on its own.

**Comment by jcsteh** [comment]
Superseded by 9215f09e (now merged).

**Pull request closed without merging**
