### PR TITLE
Fix OSARA on older versions of Mac OS

### LINKED ISSUE #349: Latest build not functioning for some mac users
When installing the latest version of osara (osara_2020.1pre-251,ef18c25e) no osara actions appear to be imported.

no speech feedback from osara
none of the osara actions show up in the actions dialogue. Specifically, none of the actions with osara in the name. 

I do have the custom actions such as “Cmd+Opt+Home Custom: Select and move to first track” But no feedback when pressing up and down arrow. F12 does not invoke shortcut help.

Have tried this on both a portable and standard installation.

I am able to use an older test build with the new key map without issue.
osara_2020.1pre-63,b630b6ef

I am running OS 10.14.5 on a late 2014 mac mini.
Have tried with reaper 6.14 and 6.12

Another RWP user experiencing the same issue is running OS 10.13 on a 2011 mac book pro.

Scott Chesworth did not have this issue on OS Catalina.

Thinking OS most likely has something to do with why this works for some and not others.

In case it is useful, here is a portable reaper with an unsuccessful install of OSARA.
https://www.dropbox.com/s/g9s9b2666wqw0j6/Broken%20portable%20reaper.zip?dl=0

Thank you to anyone able to solve this problem. Let me know if I can provide any more information.

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #349.

### CODE REVIEW

**Comment by jcsteh** [comment]
@KeithRempel, would you mind testing [this build](https://ci.appveyor.com/api/buildjobs/9gfydgl6s5wk4vq6/artifacts/installer%2Fosara_pr350-254%2C6ad2b2b8.dmg) and checking if it works for you?

**Comment by KeithRempel** [comment]
Sadly, same as the others.

**Comment by TimNoonanVoice** [comment]
Hi,

Yesterday, on MacOS 10.15.7 I had terminal errors trying to install the osara_2020.1pre-251,ef18c25e. I intended copying the errors, but didn’t get to it before a reboot.

However, after rebooting, everything worked ok. Just in case this makes any difference to the issues for earlier OS versions..

Tim

 Yesterday at 11:36 am 774 KB Disk Image
On 27 Oct 2020, at 12:52 pm, James Teh <notifications@github.com> wrote:


@KeithRempel <https://github.com/KeithRempel>, would you mind testing this build <https://ci.appveyor.com/api/buildjobs/9gfydgl6s5wk4vq6/artifacts/installer%2Fosara_pr350-254%2C6ad2b2b8.dmg> and checking if it works for you?

**Comment by jcsteh** [comment]
I've said it before and I'll say it again: I really wish I didn't have to support Mac. It's just so incredibly painful. Arrrrrggggh!

**Comment by jcsteh** [comment]
Okay, @KeithRempel, can you please try [this build](https://ci.appveyor.com/api/buildjobs/ruoqal78kcxmwvol/artifacts/installer%2Fosara_pr350-262%2C9e79a191.dmg)? Thanks.

**Comment by KeithRempel** [comment]
It works! Thanks. No detectable issues thus far. Have installed on a standard and portable copy.

And thanks for the extra effort on the mac side of things. Actually kind of hard to put into words how much it has meant to me to have such efficient and functional access to a DAW. As a life long musician, I’ve always felt I was at a huge disadvantage in the recording world up until getting up and running with OSARA. I’m sure there are differing opinions out there, but I think the reaper experience as things stand right now is monumentally superior to the alternatives.

**Comment by tbdalgaard** [comment]
Just wanted to confirm here that the latest build now works and runs under 10.13 without any issue at all.
Thanks for taking the time fixing this!

**Pull request merged**
