### PR TITLE
When moving to a track, scroll it into view visually.

### LINKED ISSUE #325: Visual display does not follow track selection
I am a sighted person who was watching a demo of OSARA today by Derek Lane. As he was demonstrating the ability of OSARA to change track selections using keystrokes, I noted that the visual display did not follow his selections. It took a few minutes for us to figure out what was happening. 

The selection started with tracks that were on screen, then he used the keystrokes to advance through higher numbered tracks. Eventually his screen reader would read the name of the track he was working on, but that track seemed to be off-screen and not part of the visual display. 

It would be nice for OSARA to update the vertical scrolling in Reaper so that the current selected track remains on the screen. Having the visual display match the screen reader would help facilitate collaborations between blind and sighted users.

Let me know if you need additional details or assistance.

### PR DESCRIPTION
**Pull request by jcsteh**
Fixes #325.

### CODE REVIEW

**Comment by jcsteh** [comment]
@nwolek, would you mind testing [this Windows build](https://ci.appveyor.com/api/buildjobs/thlemrknh8x9l7y6/artifacts/installer%2Fosara_pr326-234%2C29cbb9f6.exe) or [this Mac build](https://ci.appveyor.com/api/buildjobs/sv8n3m2bb9yibhjn/artifacts/installer%2Fosara_pr326-234%2C29cbb9f6.dmg) to see if it fixes the issue? CC @dgl1984.

**Comment by betov75** [comment]
It works fine! It centers the track. Since i'm still slightly sighted,
that's great! Thanks.

**Comment by nwolek** [comment]
Sorry for the delay. I must clarify that Derek (@dgl1984) was the one using OSARA while I watched via Zoom. That said, I downloaded your Mac build and then found keystrokes for Track: Go to next track (Command+Option+Down) and Track: Go to previous track (Command+Option+Up). I can confirm that these keeping the selected track on the screen by automatically scrolling the display. Hope that information helps.

**Comment by dgl1984** [comment]
Interesting.  Most people simply use the up and down arrow keys to go to previous and next tracks.
I wonder what is different between doing this, and the keys you discovered?

**Comment by ScottChesworth** [comment]
No difference, they're the same actions we're using, just the keystrokes assigned in the default Reaper map. Guessing @nwolek doesn't have the OSARA keymap installed yet.

**Pull request merged**
