### PR TITLE
Mac keymap update

### PR DESCRIPTION
**Pull request by jennykbrennan**

### CODE REVIEW

**Comment by jcsteh** [comment]
Hmm. I don't know why AppVeyor didn't try to build this. Irritating.

**Comment by jcsteh** [comment]
Oh I see, this is a pull request against another branch, not master.

**Comment by jennykbrennan** [comment]
Yeah, I don't think I can, can I? We weren't sure exactly how I should go about this as of yet. For now I just do what I'm told and hope for the best. :D

**Comment by jcsteh** [comment]
All good; all sorted. Thank you.

**Pull request merged**
